version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: .
    command: npm start
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
    ports:
      - "3000:3000"
    depends_on:
      - db

  worker:
    build: .
    command: npm run worker
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
    depends_on:
      - db

volumes:
  db-data:
